// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuymovuyqperpucadugb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1eW1vdnV5cXBlcnB1Y2FkdWdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNjQ4OTksImV4cCI6MjA2MDg0MDg5OX0.Hyw_ZJcr4hrqOCNksXO9NjD00_5B22ZVq4e-cdGEAx8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);